### ISSUE TITLE
Feature Request: Umfangreichere Farbpalette für die Graphen

### ISSUE THREAD

**Issue by timpritlove** [Cov19-Impfvorhersage/cov19vaccsim#3]
Derzeit sind alle Linien in einem eng gefassten Grünton-Bereich. Es wäre für die Unterscheidung der einzelnen Elemente sinnvoller, auf ein umfangreicheres Farbschema zurückzugreifen, um sofort Dinge zuordnen zu können (z.B. feste Farben für Erst-, Zweit- und Drittimpfungen etc.)

**Comment by DerGenaue** [comment]
Die Farben für Erst-, Zweit- und Drittimpfung sind eigentlich die gleichen in allen Charts.
Ich stimme dir aber zu, dass in dem 7-Tage-Chart, der ja nur Linien enthält, die Farben echt schlecht zu unterscheiden sind.
Habe deshalb in diesem Chart speziell jetzt neue Farben zugeordnet.
